import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import styles from "./ui/home.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.headCont}>
          <Link className={styles.headMenu} href="/">home</Link>
          <h1 className={styles.headTitle}>headTitle</h1>
          <div className="flex">
            <Link className={styles.headMenu} href="/login">Login</Link>
            <Link className={styles.headMenu} href="/join">Join</Link>
          </div>
        </div>
      {children}
      </body>
    </html>
  );
}
