
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/ui/globals.css';
import Reload from './ui/reload'
import LoginButton from './ui/loginButton'
import SignupButton from './ui/signupButton';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DyaBya ERP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex w-lvw h-20 items-center pl-10'> 
            <Reload />
        <div className='w-48 flex justify-around relative left-3/4'>
            <LoginButton />
        <div>
            <SignupButton />
        </div>
        </div>
      </div>
      {children}
      </body>
    </html>
  )
}
