import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/ui/globals.css";
import Reload from "./ui/layoutButtons/reloadButton";
import LoginButton from "./ui/layoutButtons/loginButton";
import SignupButton from "./ui/layoutButtons/signupButton";

export const metadata: Metadata = {
  title: "DyaBya ERP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex items-center justify-between w-full h-20 px-6 bg-gray-800 text-white">
          <Reload />
          <div className="flex space-x-4">
            <LoginButton />
            <SignupButton />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
