import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DyaByaApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="root">
          <div className="navbar">
            <div className="home">
              <Link href="/">DyaBya</Link>
              {/* <div className="homebox">로그인</div> */}
              {/* <div className="homebox">회원가입</div> */}
            </div>
          </div>
          <div className="board">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}